## Codebook
1. Raw Data
    + [Beer Names and Metrics](https://raw.githubusercontent.com/allthebits/msds6306-case-study-01/master/data/Beers.csv)
        + Variable names
            + Beer
                + The name of the beer
                + String
                + Contains non UTF-8 characters
                + No NA's
            + Beer_ID 
                + Unique Identifier of the beer
                + Integer - Range: (1 - 2692)
                + No NA's
            + ABV
                + Alcohol by volume of the beer
                + Real Number - Range (0.001 - 0.128)
                + Contains NA's
            + IBU
                + International Bitterness Units of the beer
                + Integer - Range (4 - 138)
                + Contains NA's
            + Brew_ID
                + Brewery ID associated with the beer
                + Integer - Range (1 - 558)
                + No NA's
            + Style
                + Style of the beer
                + String
                + Contains non UTF-8 characters
                + No NA's
            + Ounces
                + Ounces of the beer
                + Real Number - Values: (8.4, 12.0, 16.0, 16.9, 19.2, 24.0, 32.0)
                + Contains NA's
    + [Breweries By State](https://raw.githubusercontent.com/allthebits/msds6306-case-study-01/master/data/Breweries.csv)
        + Variable names
            + Brew_ID
                + Unique identifier of the brewery
                + Integer (1 - 558)
                + No NA's
            + Brewery
                + Name of the brewery
                + String
                + Contains non UTF-8 characters
                + No NA's
            + City
                + City where the brewery is located
                + String
                + No NA's
            + State
                + US state where the brewery is located
                + 2 Characters
                + No NA's
                + 51 Unique Values
2. Final Merged Data
    + Beer Names and Metrics
        + Info
            + Dataframe: beer
            + CSV name: data/tidy/beer.csv
        + Variable names
            + Beer
                + The name of the beer
                + String
                + UTF-8 characters only
                + No NA's
            + Beer_ID 
                + Unique Identifier of the beer
                + Integer - Range: (1 - 2692)
                + No NA's
            + ABV
                + Alcohol by volume of the beer
                + Real Number - Range (0.001 - 0.128)
                + Contains NA's
            + IBU
                + International Bitterness Units of the beer
                + Integer - Range (4 - 138)
                + Contains NA's
            + Brew_ID
                + Brewery ID associated with the beer
                + Integer - Range (1 - 558)
                + No NA's
            + Style
                + Style of the beer
                + String
                + UTF-8 characters only
                + No NA's
            + Ounces
                + Ounces of the beer
                + Real Number - Values: (8.4, 12.0, 16.0, 16.9, 19.2, 24.0, 32.0)
                + No NA's
    + Breweries By State
        + Info
            + Dataframe: brewery
            + CSV name: data/tidy/brewery.csv
        + Variable names
            + Brew_ID
                + Unique identifier of the brewery
                + Integer (1 - 558)
                + No NA's
            + Brewery
                + Name of the brewery
                + String
                + UTF-8 characters only
                + No NA's
            + City
                + City where the brewery is located
                + String
                + No NA's
            + State
                + US state where the brewery is located
                + 2 Characters
                + No NA's
                + 51 Unique Values
    + Combined Beer and Brewery Names and Metrics
        + Info
            + Dataframe: beerbrew
            + CSV name: data/tidy/beerbrew.csv
        + Variable names
            + Beer_ID
                + Integer - Range: (1 - 2692)
                + No NA's
            + Beer
                + String - Range: (1 - 1372)
                + No NA's
            + Style    
                + String
                + No NA's
            + Ounces
                + Real Number - Values: (8.4, 12.0, 16.0, 16.9, 19.2, 24.0, 32.0)
                + No NA's                
            + ABV
                + Real Number - Range (0.027 - 0.125)
                + No NA's
            + IBU
                + Integer - Range (4 - 138)
                + No NA's
            + Brew_ID
                + Integer - Range (1 - 547)
                + No NA's
            + Brewery
                + String
                + No NA's
            + City 
                + String
                + No NA's
            + State
                + 2 Characters - 50 Unique Values
                + No NA's
     + Breweries by State
          + Info
             + Dataframe: breweryByState
             + CSV name: data/tidy/BreweryByState.csv 
          + Variable names    
            + State
                + 2 Characters - 50 Unique Values
                + No NA's
            + Breweries
                + Integer - Range (1 - 47)
                + No NA's          
3. Data Modifications
    + Load the Beer and Breweries datasets, rename the columns, sort beer dataset
        + Define variables to be used throughout the document
        + Define base/root URL to load the data
        + Define the String URL's for the Beer and Brewery datasets
        + Load the Beer and Brewery Datasets
    + Convert UTF-8 format character data in Dataframes for Beer and Brewery    
        + Convert UTF-8 format in "beer$Name"
        + Convert UTF-8 format in "beer$Style"
        + Convert UTF-8 format in "beer$Style"
    + Modify column/variable names on the Dataframes for Beer and Brewery
        + Rename column "Name" to "Beer" in beer df
        + Rename column "Brewery_id"" to "Brew_ID" in beer df
        + Rename column "Name" to "Brewery" in brewery df
        + Arrange beer df by Brew_ID
        + Remove duplicates with all columns other than Brew_ID as criteria for removal
        + Remove row.names column        
4. Tidy dataset
    + beer
    + beerbrew
         + Merge data frames
         + Sort columns
         + NA removal (all)
    + brewery
    + BreweryByState
         + Count breweries per state
         + Remove Washington DC
         + Rename column "Brewery_id"" to "Brew_ID" in beer df
         + Sort by most to least    
5.  Recipe for Tidy Dataset
     + Commented R script file
         + Tidy_Recipe.R    
