---
title: "Beers and Breweries Analysis"
subtitle: "Case Study 01 - MSDS 6306 Section 402"
author:
- Luke Pierce <lepierce@smu.edu>
- Lokesh Maganti <lmaganti@smu.edu>
- Andrew Walch <awalch@smu.edu>
- MJKelleher <mikek@smu.edu>
date: "February 14, 2018"
output: 
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE, echo=TRUE}
# Clean the workspace, remove all existing Objects
rm(list=ls())
```

## Appendix
### Source Code
#### Required Libraries
1. deplyr  - To Install: 1install.packages("deplyr")
1. ggplot2 - To Install: 1install.packages("ggplot2")
1. doBy    - To Install: 1install.packages("doBy")

```{r, results='hide', message=FALSE, warning=FALSE}
library(dplyr)
```


```{r}
# Define the 'root' URL where we will read the data from
data_root_url <- "https://raw.githubusercontent.com/allthebits/msds6306-case-study-01/master/data/";

# Define the String URL's for the Beer and Brewery datasets
beer_url <- paste(data_root_url, "Beers.csv", sep="");
brewery_url <- paste(data_root_url, "Breweries.csv", sep="");

# Load the Beer and Brewery Datasets
beer <- read.csv(url(beer_url), header = TRUE, sep=",", row.names = NULL)
brewery <- read.csv(url(brewery_url), header = TRUE, sep=",", row.names = NULL)
```


```{r}
#===============================================================================
# Modify column/variable names on the Dataframes for Beer and Brewery

# in beer df rename column "Name" to "Beer" 
beer <- rename(beer, Beer = Name)

# in beer df rename column "Brewery_id"" to "Brew_ID" 
beer <- rename(beer, Brew_ID = Brewery_id)

# in brewery df rename column "Name" to "Brewery" 
brewery <- rename(brewery, Brewery = Name)

# Arrange beer df by Brew_ID
beer <- arrange(beer, (Brew_ID))
```


```{r, results='hide', message=FALSE, warning=FALSE}
library(ggplot2)
```
```{r}
#===============================================================================
# Case Study 01 : Question 01) Breweries per state?
# Count breweries per state
BwryPerState <- count(brewery, State)

# in beer df rename column "Brewery_id"" to "Brew_ID" 
BwryPerState <- rename(BwryPerState, Breweries = n)

summary(BwryPerState)
utils::View(BwryPerState)

# Sort by most to least
BwryPerState <- arrange(BwryPerState, desc(Breweries))

ggplot(BwryPerState, aes(x=reorder(State, Breweries), y=(Breweries), fill = "red")) + geom_bar(stat='identity') + coord_flip() + labs(title ="Breweries Per State", x = "State", y = "Number of Breweries") + theme(legend.position="none")
```



```{r}
#===============================================================================
# Case Study 01 : Question 02) Merge beer and brewery data. Print first and last 6 observations
# QC
str(beer)
summary(beer)
str(brewery)
summary(brewery)

# Merge data frames
beerbrew <- dplyr::inner_join(beer, brewery, by = "Brew_ID")
summary(beerbrew)

# Sort columns (one option)
beerbrew <- beerbrew[c("Beer_ID", "Beer", "Style", "Ounces", "ABV", "IBU", "Brew_ID", "Brewery", "City", "State")]

summary(beerbrew)
str(beerbrew)
utils::View(beerbrew)

# Check beerbrew

head(beerbrew,6)
tail(beerbrew,6)
```


```{r}
#===============================================================================
# Case Study 01 : Question 03) Report NA in each column
sapply(beerbrew, function(x) sum(is.na(x)))
```

```{r, results='hide', message=FALSE, warning=FALSE}
library(doBy)
```
```{r}
#===============================================================================
# Case Study 01 : Question 04) Median ABV and IBU by state. Plot barchart.
#NA removal (all)
beerbrew <- beerbrew[complete.cases(beerbrew), ]

utils::View(beerbrew)

# Calculate median values for each obs of ABV and IBU by state using DoBy

MedianABV <- summaryBy(ABV ~ State, data = beerbrew, FUN = median)
MedianIBU <- summaryBy(IBU ~ State, data = beerbrew, FUN = median)
utils::View(MedianABV)
utils::View(MedianIBU)

# Merge into one df
ABV_IBU_median <- dplyr::inner_join(MedianABV, MedianIBU, by = "State")

summary(ABV_IBU_median)
str(ABV_IBU_median)

# TODO: normalize and dual barplot ggplot here *********************************
```




```{r}
#===============================================================================
# Case Study 01 : Question 05) State with highest ABV? Highest IBU?
# Most alcoholic beer (Kentucky)
dplyr::top_n(beerbrew, 1, ABV)

# Most bitter beer (Oregon)
dplyr::top_n(beerbrew, 1, IBU)
```


```{r}
#===============================================================================
# Case Study 01 : Question 06) Summary Statistics for the ABV variable
summary(beerbrew$ABV)
```


```{r}
#===============================================================================
# Case Study 01 : Question 07) Is there an apparent relationship between the 
#                              bitterness of the beer and its alcoholic content? 
#                              Draw a scatter plot.

ggplot(beerbrew, aes(x=IBU, y=ABV)) +
    geom_point(shape=1) +    # Use hollow circles
    geom_smooth(method=lm)   # Add linear regression line 
                             #  (by default includes 95% confidence region)
```